// Mock data for demo purposes when Keycloak/OpenVPN servers are not connected

export const mockUsers = [
  {
    id: "u1",
    username: "admin",
    email: "admin@company.com",
    firstName: "System",
    lastName: "Administrator",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 90 * 24 * 60 * 60 * 1000,
    groups: ["admins", "developers"],
    roles: ["admin", "user"],
  },
  {
    id: "u2",
    username: "john.doe",
    email: "john.doe@company.com",
    firstName: "John",
    lastName: "Doe",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 60 * 24 * 60 * 60 * 1000,
    groups: ["developers"],
    roles: ["developer", "user"],
  },
  {
    id: "u3",
    username: "jane.smith",
    email: "jane.smith@company.com",
    firstName: "Jane",
    lastName: "Smith",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 45 * 24 * 60 * 60 * 1000,
    groups: ["developers", "qa-team"],
    roles: ["developer", "user"],
  },
  {
    id: "u4",
    username: "mike.wilson",
    email: "mike.wilson@company.com",
    firstName: "Mike",
    lastName: "Wilson",
    enabled: true,
    emailVerified: false,
    createdTimestamp: Date.now() - 30 * 24 * 60 * 60 * 1000,
    groups: ["support"],
    roles: ["support", "user"],
  },
  {
    id: "u5",
    username: "sarah.johnson",
    email: "sarah.johnson@company.com",
    firstName: "Sarah",
    lastName: "Johnson",
    enabled: false,
    emailVerified: true,
    createdTimestamp: Date.now() - 120 * 24 * 60 * 60 * 1000,
    groups: ["marketing"],
    roles: ["user"],
  },
  {
    id: "u6",
    username: "david.brown",
    email: "david.brown@company.com",
    firstName: "David",
    lastName: "Brown",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 15 * 24 * 60 * 60 * 1000,
    groups: ["developers"],
    roles: ["developer", "user"],
  },
  {
    id: "u7",
    username: "emily.davis",
    email: "emily.davis@company.com",
    firstName: "Emily",
    lastName: "Davis",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    groups: ["qa-team"],
    roles: ["tester", "user"],
  },
  {
    id: "u8",
    username: "robert.taylor",
    email: "robert.taylor@company.com",
    firstName: "Robert",
    lastName: "Taylor",
    enabled: true,
    emailVerified: false,
    createdTimestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    groups: ["developers"],
    roles: ["developer", "user"],
  },
  {
    id: "u9",
    username: "lisa.anderson",
    email: "lisa.anderson@company.com",
    firstName: "Lisa",
    lastName: "Anderson",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 25 * 24 * 60 * 60 * 1000,
    groups: ["support", "qa-team"],
    roles: ["support", "user"],
  },
  {
    id: "u10",
    username: "james.martinez",
    email: "james.martinez@company.com",
    firstName: "James",
    lastName: "Martinez",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 50 * 24 * 60 * 60 * 1000,
    groups: ["admins"],
    roles: ["admin", "user"],
  },
  {
    id: "u11",
    username: "anna.white",
    email: "anna.white@company.com",
    firstName: "Anna",
    lastName: "White",
    enabled: true,
    emailVerified: true,
    createdTimestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    groups: ["developers"],
    roles: ["developer", "user"],
  },
  {
    id: "u12",
    username: "chris.lee",
    email: "chris.lee@company.com",
    firstName: "Chris",
    lastName: "Lee",
    enabled: false,
    emailVerified: true,
    createdTimestamp: Date.now() - 80 * 24 * 60 * 60 * 1000,
    groups: ["support"],
    roles: ["support", "user"],
  },
]

export const mockGroups = [
  {
    id: "g1",
    name: "admins",
    path: "/admins",
    memberCount: 2,
    subGroups: [],
  },
  {
    id: "g2",
    name: "developers",
    path: "/developers",
    memberCount: 5,
    subGroups: [
      { id: "g2-1", name: "frontend", path: "/developers/frontend", memberCount: 2 },
      { id: "g2-2", name: "backend", path: "/developers/backend", memberCount: 3 },
    ],
  },
  {
    id: "g3",
    name: "qa-team",
    path: "/qa-team",
    memberCount: 3,
    subGroups: [],
  },
  {
    id: "g4",
    name: "support",
    path: "/support",
    memberCount: 3,
    subGroups: [],
  },
  {
    id: "g5",
    name: "marketing",
    path: "/marketing",
    memberCount: 1,
    subGroups: [],
  },
]

export const mockRoles = [
  {
    id: "r1",
    name: "admin",
    description: "Full system administrator access",
    composite: true,
    clientRole: false,
    containerId: "master",
    userCount: 2,
  },
  {
    id: "r2",
    name: "developer",
    description: "Development team access",
    composite: false,
    clientRole: false,
    containerId: "master",
    userCount: 5,
  },
  {
    id: "r3",
    name: "user",
    description: "Basic user access",
    composite: false,
    clientRole: false,
    containerId: "master",
    userCount: 12,
  },
  {
    id: "r4",
    name: "support",
    description: "Customer support access",
    composite: false,
    clientRole: false,
    containerId: "master",
    userCount: 3,
  },
  {
    id: "r5",
    name: "tester",
    description: "QA testing access",
    composite: false,
    clientRole: false,
    containerId: "master",
    userCount: 2,
  },
  {
    id: "r6",
    name: "viewer",
    description: "Read-only access",
    composite: false,
    clientRole: false,
    containerId: "master",
    userCount: 4,
  },
]

export const mockSessions = [
  {
    id: "s1",
    username: "john.doe",
    userId: "u2",
    ipAddress: "192.168.1.100",
    start: Date.now() - 2 * 60 * 1000,
    lastAccess: Date.now() - 30 * 1000,
    clients: ["admin-portal", "api-gateway"],
  },
  {
    id: "s2",
    username: "jane.smith",
    userId: "u3",
    ipAddress: "192.168.1.101",
    start: Date.now() - 15 * 60 * 1000,
    lastAccess: Date.now() - 2 * 60 * 1000,
    clients: ["admin-portal"],
  },
  {
    id: "s3",
    username: "admin",
    userId: "u1",
    ipAddress: "10.0.0.1",
    start: Date.now() - 60 * 60 * 1000,
    lastAccess: Date.now() - 5 * 60 * 1000,
    clients: ["admin-portal", "api-gateway", "monitoring"],
  },
  {
    id: "s4",
    username: "david.brown",
    userId: "u6",
    ipAddress: "192.168.1.150",
    start: Date.now() - 30 * 60 * 1000,
    lastAccess: Date.now() - 10 * 60 * 1000,
    clients: ["api-gateway"],
  },
  {
    id: "s5",
    username: "emily.davis",
    userId: "u7",
    ipAddress: "192.168.1.175",
    start: Date.now() - 45 * 60 * 1000,
    lastAccess: Date.now() - 15 * 60 * 1000,
    clients: ["admin-portal"],
  },
]

export const mockVPNGroups = [
  {
    id: "vg1",
    name: "developers",
    description: "Development team VPN access",
    prop_autologin: true,
  },
  {
    id: "vg2",
    name: "admins",
    description: "System administrators",
    prop_autologin: true,
  },
  {
    id: "vg3",
    name: "contractors",
    description: "External contractors",
    prop_autologin: false,
  },
  {
    id: "vg4",
    name: "support",
    description: "Customer support team",
    prop_autologin: false,
  },
]

export const mockVPNUsers = [
  {
    id: "vpn1",
    username: "john.doe",
    email: "john.doe@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    assignedIP: "10.8.0.2",
    group: "developers",
    prop_autologin: true,
    prop_admin: false,
  },
  {
    id: "vpn2",
    username: "jane.smith",
    email: "jane.smith@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: "active" as const,
    assignedIP: "10.8.0.3",
    group: "developers",
    prop_autologin: true,
    prop_admin: false,
  },
  {
    id: "vpn3",
    username: "mike.wilson",
    email: "mike.wilson@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: "inactive" as const,
    assignedIP: "10.8.0.4",
    group: "support",
    prop_autologin: false,
    prop_admin: false,
  },
  {
    id: "vpn4",
    username: "sarah.johnson",
    email: "sarah.johnson@company.com",
    enabled: false,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: "suspended" as const,
    assignedIP: "10.8.0.5",
    group: "contractors",
    prop_autologin: false,
    prop_admin: false,
  },
  {
    id: "vpn5",
    username: "david.brown",
    email: "david.brown@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    assignedIP: "10.8.0.6",
    group: "developers",
    prop_autologin: true,
    prop_admin: false,
  },
  {
    id: "vpn6",
    username: "admin",
    email: "admin@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    assignedIP: "10.8.0.1",
    group: "admins",
    prop_autologin: true,
    prop_admin: true,
  },
  {
    id: "vpn7",
    username: "robert.taylor",
    email: "robert.taylor@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "inactive" as const,
    assignedIP: "10.8.0.7",
    prop_autologin: false,
    prop_admin: false,
  },
  {
    id: "vpn8",
    username: "lisa.anderson",
    email: "lisa.anderson@company.com",
    enabled: true,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    assignedIP: "10.8.0.8",
    group: "support",
    prop_autologin: false,
    prop_admin: false,
  },
]

export const mockVPNConnections = [
  {
    id: "conn1",
    username: "john.doe",
    realAddress: "203.0.113.45:51234",
    virtualAddress: "10.8.0.2",
    bytesReceived: 15234567,
    bytesSent: 8765432,
    connectedSince: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "connected" as const,
  },
  {
    id: "conn2",
    username: "jane.smith",
    realAddress: "198.51.100.78:48765",
    virtualAddress: "10.8.0.3",
    bytesReceived: 8976543,
    bytesSent: 4321098,
    connectedSince: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: "connected" as const,
  },
  {
    id: "conn3",
    username: "admin",
    realAddress: "192.0.2.100:52341",
    virtualAddress: "10.8.0.1",
    bytesReceived: 45678901,
    bytesSent: 23456789,
    connectedSince: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: "connected" as const,
  },
  {
    id: "conn4",
    username: "david.brown",
    realAddress: "203.0.113.89:49876",
    virtualAddress: "10.8.0.6",
    bytesReceived: 2345678,
    bytesSent: 1234567,
    connectedSince: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    status: "connected" as const,
  },
  {
    id: "conn5",
    username: "lisa.anderson",
    realAddress: "198.51.100.123:50123",
    virtualAddress: "10.8.0.8",
    bytesReceived: 5678901,
    bytesSent: 2345678,
    connectedSince: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    status: "connected" as const,
  },
]

export const mockConfigs = [
  {
    id: "cfg1",
    name: "john.doe-windows",
    username: "john.doe",
    platform: "windows" as const,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    lastDownloaded: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
  },
  {
    id: "cfg2",
    name: "john.doe-macos",
    username: "john.doe",
    platform: "macos" as const,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    lastDownloaded: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
  },
  {
    id: "cfg3",
    name: "jane.smith-linux",
    username: "jane.smith",
    platform: "linux" as const,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    lastDownloaded: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
  },
  {
    id: "cfg4",
    name: "admin-mobile",
    username: "admin",
    platform: "mobile" as const,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    lastDownloaded: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
  },
  {
    id: "cfg5",
    name: "david.brown-windows",
    username: "david.brown",
    platform: "windows" as const,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
  },
  {
    id: "cfg6",
    name: "sarah.johnson-macos",
    username: "sarah.johnson",
    platform: "macos" as const,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    lastDownloaded: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: "revoked" as const,
  },
]

export const mockRecentActivity = [
  {
    id: "a1",
    type: "login" as const,
    user: "john.doe",
    description: "Signed in from 192.168.1.100",
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: "a2",
    type: "vpn_connect" as const,
    user: "jane.smith",
    description: "Connected to VPN from 198.51.100.78",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "a3",
    type: "user_created" as const,
    user: "admin",
    description: "Created new user: robert.taylor",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "a4",
    type: "role_assigned" as const,
    user: "admin",
    description: "Assigned developer role to david.brown",
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "a5",
    type: "config_generated" as const,
    user: "david.brown",
    description: "Generated VPN config for Windows",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "a6",
    type: "vpn_disconnect" as const,
    user: "mike.wilson",
    description: "Disconnected from VPN",
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: "a7",
    type: "password_reset" as const,
    user: "admin",
    description: "Reset password for emily.davis",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "a8",
    type: "login" as const,
    user: "admin",
    description: "Signed in from 10.0.0.1",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
]
